pluginManagement {
    includeBuild('../build-logic') //common will use build-logic project as a plugin but we dont know which convention it will use

    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}
rootProject.name = 'istad-common'
include 'istad-common-domain'
include 'istad-common-restapi'